version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=quickstart
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - codecampnet

  quickstart:
    # image: ghcr.io/bcc2021-team-jee-to-mp-quarkus-etc/wf-starter:da363759f570bc6a3e0ffe983c8717e19a615591
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./src/main/docker/Dockerfile
    restart: always
    environment:
      - DB_HOST=postgres
    #ports:
    #  - "8080:8080"
    #  - "9990:9990"
    networks:
      - codecampnet

  pg-admin:
    depends_on:
      - postgres
    build:
      context: ./local-config
      dockerfile: ./dockerfile_for_pgadmin
    restart: always
    environment:
      - "PGADMIN_DEFAULT_EMAIL=codecamp@baloise.com"
      - "PGADMIN_DEFAULT_PASSWORD=password"
    volumes:
      - "./local-config/servers.json:/pgadmin4/servers.json"
    ports:
      - "8432:80"
    networks:
      - codecampnet
networks:
  codecampnet:
