FROM dpage/pgadmin4
USER pgadmin
RUN mkdir -p  /var/lib/pgadmin/storage/codecamp_baloise.com
COPY ./pgpassfile /var/lib/pgadmin/storage/codecamp_baloise.com/
USER root
RUN chown pgadmin:pgadmin /var/lib/pgadmin/storage/codecamp_baloise.com/pgpassfile
RUN chmod 0600 /var/lib/pgadmin/storage/codecamp_baloise.com/pgpassfile
USER pgadmin
ENTRYPOINT ["/entrypoint.sh"]
